### ISSUE TITLE
虽然没用配出来, 但是还是谢谢老板

### ISSUE THREAD

**Issue by smamqm** [exiahuang/SalesforceXyTools#1]
我的mavensmate可以用, 但是SFDC-XY用不了, 我在配一下, 这种能在sublime里面跑soql的插件我找了很久了, 真的很不错, 谢谢

**Comment by exiahuang** [comment]
有3种方式可以使用，一种是oauth, password, 还有就是直接用Mavesmate的session.
mavensmate-destop v0.0.10 或者以下版本，不需要设置，直接能使用的。
mavensmate-destop v0.0.11-beta.2以上版本，由于用了oauth2认证，需要设置下mavesmate,
可以参考https://github.com/exiahuang/SalesforceXyTools进行配置
设置password或者用旧版的mavensmate比较方便。

**Comment by smamqm** [comment]
谢谢大佬, 我再试试.
对了, 我的mavensmate配置了https代理的, 这个有影响吗?

**Comment by exiahuang** [comment]
应该没有关系的，
