### ISSUE TITLE
Metadata missing for Test calss created in "Create Test Code" module

### ISSUE THREAD

**Issue by pawanpatel85** [exiahuang/SalesforceXyTools#6]
I have created class in org and with SFDC-XY created test class using "Create test code" module. but I can not deploy that test class and getting error that Metadata is null!

What would be best way to deploy test class that has been created?

**Comment by exiahuang** [comment]
@pawanpatel85 

①If you use 【Right click, SFDC-XY Code Creator >Create test code】， it just create code in your local pc. You can use "Deploy" to deploy your code.  Please read this [article](http://salesforcexytools.com/SalesforcexytoolsForSublime/SalesforceXytoolsForSublime-102-TestClass-Creater.html).

② You alse can create apex code in [Metadata-> New ApexClass] manually. [Please read this](http://salesforcexytools.com/SalesforcexytoolsForSublime/SalesforceXytoolsForSublime-003-SFDC-Develop.html).

③About Deploy ,  you can read this one.
[Deploy Package](http://salesforcexytools.com/SalesforcexytoolsForSublime/SalesforceXytoolsForSublime-009-DeployPackage-Builder.html)

④ more help:
http://salesforcexytools.com/categories/SalesforcexytoolsForSublime/

**Comment by pawanpatel85** [comment]
Thanks for info. I wasn't aware of this. sorry.

**Comment by pawanpatel85** [comment]
Issue resolved. Thanks @exiahuang
